### ISSUE TITLE
[ECMAScript 6: 화살표 함수와 메소드 정의] 문장 해석 추천

### ISSUE THREAD

**Issue by pouu69** [FEDevelopers/tech.description#11]
`That is unfortunate, because the subroutine has no use for its own this, but it shadows the this of the surrounding method, making it inaccessible.`

`그것은 불행하다, 왜냐면 서브루틴은 그 자신의 this를 사용하지 못하기 때문이다. 하지만 그것은 this를 둘러싸고 있는 메서드들에 접근이 어렵게 숨긴다.`

전 여기까지인거 같습니다. 좀더 디벨롭 해서 해석 바래요 ㅋㅋ

**Comment by apple77y** [comment]
여전히 무슨 말인지 모르겠는 것...

**Comment by apple77y** [comment]
수정: https://github.com/FEDevelopers/tech.description/wiki/ECMAScript-6:-%ED%99%94%EC%82%B4%ED%91%9C-%ED%95%A8%EC%88%98%EC%99%80-%EB%A9%94%EC%86%8C%EB%93%9C-%EC%A0%95%EC%9D%98/_compare/a736abf2a28fecdb2ead978760b62d41dbd27cb3...c2fcd2ea7b446e97ee72326e1a7d92e1611470bf
