### ISSUE TITLE
[ECMAScript 6: 화살표 함수와 메소드 정의] 구문 수정

### ISSUE THREAD

**Issue by pouu69** [FEDevelopers/tech.description#12]
5.1  섹션 바로 아래
“(maximally minimal classes)[http://wiki.ecmascript.org/doku.php?id=strawman:maximally_minimal_classes]”라고

->

“[maximally minimal classes](http://wiki.ecmascript.org/doku.php?id=strawman:maximally_minimal_classes])”라고

수정

**Comment by apple77y** [comment]
수정: https://github.com/FEDevelopers/tech.description/wiki/ECMAScript-6:-%ED%99%94%EC%82%B4%ED%91%9C-%ED%95%A8%EC%88%98%EC%99%80-%EB%A9%94%EC%86%8C%EB%93%9C-%EC%A0%95%EC%9D%98/_compare/2e734dfc726ba02d516520126de64ab24288c0b2...218092c01c2901903c0d4ab4fc9a529f7c59b806
