### ISSUE TITLE
[함수형 프로그래밍 1탄] 수정사항

### ISSUE THREAD

**Issue by pouu69** [FEDevelopers/tech.description#14]
`불변성 섹션 위부분`

자바스크립트, 자바, 씨샵과 같은 명령형 프로그래밍 언어에서는 어디에서나 부작용이 존재한다. 이건 디버깅을 어렵게 한다. 왜냐하면 변수 값이 바뀔 수 있기 때문이다. 그래서 변수가 잘못된 값으로 **바뀌어서**  **바뀌어서** 버그가 발생할 때, 어디를 봐야할까? 소스 코드 모든 곳을 봐야할까? 그 방법은 썩 좋지 못하다.

바뀌어서가 두번 반복됌

**Comment by apple77y** [comment]
👍
