### ISSUE TITLE
오타 수정

### ISSUE THREAD

**Issue by SonOfDevil** [FEDevelopers/tech.description#15]
https://github.com/FEDevelopers/tech.description/wiki/%EB%8F%94-%EC%A1%B0%EC%9E%91

4) HTML 요소를 접근하는 방법 (MDN Reference)

innerHTML은 element 자손의 HTML 구문을 가져오거나 설정할 때 사용한다.

// get the HTML of "element"
var content = element.innerHTML;

// set the HTML of "otherElement"

otherElement.innterHTML = content;
**otherElement.innerHTML = content;**

**Comment by apple77y** [comment]
👍 

수정했습니다. 감사합니다!!
