### ISSUE TITLE
[es6 비동기 프로그래밍] 오타수정 

### ISSUE THREAD

**Issue by jeonghwan-kim** [FEDevelopers/tech.description#16]
> for,while`과 같은 루프

마크다운 문법 오타인것 같습니다.

**Comment by pouu69** [comment]
https://github.com/FEDevelopers/tech.description/wiki/%5BES6%5D-%EB%B9%84%EB%8F%99%EA%B8%B0-%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D/_compare/d012bb01bb29859c1bf95e1fa6da595ca331bfa6...634ec4db06400ed7c737296ab76cbb0ee38c29e3#diff-b8a5d2e167d5792a409f993f8abf4d7b

수정하였습니다. 감사합니다.
