### ISSUE TITLE
[함수형 프로그래머가 되고 싶다고? (Part 3)] 오타 확인

### ISSUE THREAD

**Issue by pouu69** [FEDevelopers/tech.description#26]
맨마지막 부분에서 

> 그래서 함수 합성의 장점은 한계가 있으므로 이 두 개의 함수를 `결함(marry)`할 수 없게 되었다. 강력한 기능이지만, 너무 아쉽다.

 결함(marry)  -> 결합 

아닐가요?

**Comment by apple77y** [comment]
수정 완료
