### ISSUE TITLE
위키리스트 넘버링 삭제 요청

### ISSUE THREAD

**Issue by pouu69** [FEDevelopers/tech.description#30]
위키리스트에 넘버링 하는거 삭제 하고 없애는 방향으로 가면 좋을거 같습니다.

시리즈별로 올릴때마다 순서대로 봐야 좋고, 카테고리할때 뭉쳐서 하면좋은데

그럴때마다 넘버를 바꿔야해서 너무 귀찮습니다.

**Comment by apple77y** [comment]
네, 삭제하셔도 무방하겠습니다.
작업 진행해주세요.
