### ISSUE TITLE
[오타 신고] 함수형 프로그래머가 되고 싶다고? (Part 5)

### ISSUE THREAD

**Issue by pouu69** [FEDevelopers/tech.description#36]
[함수형 프로그래머가 되고 싶다고? (Part 5)](https://github.com/FEDevelopers/tech.description/wiki/%ED%95%A8%EC%88%98%ED%98%95-%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8%EA%B0%80-%EB%90%98%EA%B3%A0-%EC%8B%B6%EB%8B%A4%EA%B3%A0%3F-(Part-5))

1. 
```
하지만 멀테 쓰레드에는 2가지 주요 문제점이 있다. 
```
```
멀테 -> 멀티
```

2.
```
하지만, 순서를 중요하게 생각지 않고, 모든 것을 병렬로 처리해벼리면 어떻게 될까?
```
```
처리해벼리면 -> 처리해버리면
```

**Comment by pouu69** [comment]
3.
```
 만약 자바나 다른 언어에서 제네렉을 사용해왔다면
```
```
제네렉 -> 제네릭
```

**Comment by apple77y** [comment]
수정했습니다 👍

**Comment by jeonghwan-kim** [comment]
4.
```
호출될 대 → 호출될 때 
```

**Comment by apple77y** [comment]
@jeonghwan-kim 

수정했습니다 👍
