### ISSUE TITLE
번역 예정: Hot reloading and time travel debugging: what are they?

### ISSUE THREAD

**Issue by apple77y** [FEDevelopers/tech.description#37]
원문: https://code-cartoons.com/hot-reloading-and-time-travel-debugging-what-are-they-3c8ed2812f35#.h493rgis2

**Comment by pouu69** [comment]
ㄷㅏㄷ으시오

**Comment by apple77y** [comment]
완료: https://github.com/FEDevelopers/tech.description/wiki/Hot-reloading과-Time-travel-debugging:-각각-무엇일까%3F
