### ISSUE TITLE
[공동 번역] es6features 입니다.

### ISSUE THREAD

**Issue by pouu69** [FEDevelopers/tech.description#39]
@apple77y 님이  
[https://github.com/FEDevelopers/es6features](https://github.com/FEDevelopers/es6features) 을 포크 해서 `translate-ko`  브랜치 생성해놨습니다.

ES6 includes the following new features:
1. arrows
2. classes
3. enhanced object literals
4. template strings
5. destructuring
6. default + rest + spread
7. let + const
8. iterators + for..of
9. generators
10. unicode
11. modules
12. module loaders
13. map + set + weakmap + weakset
14. proxies
15. symbols
16. subclassable built-ins
17. promises
18. math + number + string + array + object APIs
19. binary and octal literals
20. reflect api
21. tail calls

위 21가지 챕터 중 하고싶은 것 7개씩 적어주세요.  중복되는 건 서로간에 협의해서 진행하도록 하겠습니다.
( 미참가 하고싶은신분은 미참가로 해주세요~ 부담없이 해주세요~ 저흰 항상 자율이기때문에 )

**Comment by apple77y** [comment]
@pouu69 @jeonghwan-kim 

제가 먼저 7개를 선택해서 해장 저장소에 이슈로 등록해놨습니다.
이번 번역은 개인이 별도의 개발 브랜치를 따서 PR하는 방식으로 진행하겠습니다.
관련 이슈는 아래에서 진행하도록 하겠습니다.

https://github.com/FEDevelopers/es6features/issues

**Comment by pouu69** [comment]
이거 재밋는 부분 먼저 선수 치셨군요.

**Comment by apple77y** [comment]
@pouu69 

ㅋㅋㅋㅋ선착순인 것 같아서..

**Comment by pouu69** [comment]
저도 다 골랐어요

**Comment by jeonghwan-kim** [comment]
그럼 나머지는 제가 할께요 ^^

**Comment by apple77y** [comment]
해당 이슈는 정리 되었으므로 닫겠습니다.
