### ISSUE TITLE
번역 예정

### ISSUE THREAD

**Issue by pouu69** [FEDevelopers/tech.description#40]
http://www.theodo.fr/blog/2016/03/getting-started-with-react-redux-and-immutable-a-test-driven-tutorial-part-2/

**Comment by storymessinger** [comment]
https://leanpub.com/setting-up-es6/read#sec_webpack-babel 에서 (Chapter 3.3) Browser Setup: ES6 via webpack and Babel

**Comment by pouu69** [comment]
https://github.com/FEDevelopers/tech.description/wiki/TDD%EA%B8%B0%EB%B0%98-React,Redux,Immutable-%EC%8B%9C%EC%9E%91%ED%95%98%EA%B8%B0-(2)

완료
