### ISSUE TITLE
[번역예정] Vue.js Is Good, But Is It Better Than Angular Or React?

### ISSUE THREAD

**Issue by jeonghwan-kim** [FEDevelopers/tech.description#53]
http://www.valuecoders.com/blog/technology-and-apps/vue-js-comparison-angular-react/

**Comment by pouu69** [comment]
기대됩니다. VUEJS가 얼마나좋을지..

**Comment by jeonghwan-kim** [comment]
다 장단점이 있더라구요 (공부하다 현타옴)

**Comment by gloomygentleman** [comment]
요즘 vue 보고 있는데 기대되네요 ㅋㅋㅋ
