### ISSUE TITLE
[오타신고] 과연 Vue.js 앵귤러나 리엑트보다 좋을까?

### ISSUE THREAD

**Issue by pouu69** [FEDevelopers/tech.description#54]
원문 : `Vue.js의 기본 개념이 좀 확실해 졌으면 하는데...... 앵률러, 리엑트와 비교해 보겠습니다. 앵귤러부터 시작해보죠.`
->
`앵률러` -> `앵귤러`

**Comment by pouu69** [comment]
원문 : `Vue.js는 더 유연하고, (앵귤러 보다) 관점이 적은 솔류션이다 `
->
`솔류션` => `솔루션`

**Comment by pouu69** [comment]
원문 : `객체나 배열을 인터폴레이션이 안됩니다`
->
`객체나 배열을` -> `객체나 배열은`

**Comment by jeonghwan-kim** [comment]
감사합니다. 수정하고 페북 프론트앤드개발그룹에 공유했습니다
