### ISSUE TITLE
[오타신고] Webpack 2 Tree Shaking Configuration

### ISSUE THREAD

**Issue by pouu69** [FEDevelopers/tech.description#57]
1. `가장 기대되는 기는 중 하나다. ` -> `가장 기대되는 기능 중 하나다`

2. `새로운 .babalrc은 아래와 같다.` -> `새로운 .babelrc은 아래와 같다.`

**Comment by apple77y** [comment]
https://github.com/FEDevelopers/tech.description/wiki/Webpack-2-Tree-Shaking-Configuration/_compare/afb5bea0dc3e6007fa29e51309ada50755df2e6f...d8fbe28cc62475322f3284fa428f9ea33e3622cc

수정 완료
