### ISSUE TITLE
[오타신고] Webpack2와 모듈번들링을 위한 초보자 가이드

### ISSUE THREAD

**Issue by ppeeou** [FEDevelopers/tech.description#58]
// webpack.config.js
const webpack = require('webpack')
const path = require('path')

const extractCommons = new webpack.optimize.CommonsChunkPlugin({
  name: 'commons',
  filename: 'common.js'
})

const ExtractTextPlugin = require('extract-text-webpack-plugin')
const extractCSS = new ExtractTextPlugin('[name].bundle.css')
const config = {
  context: path.resolve(__dirname, 'src'),
  entry: './app.js',
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: 'bundle.js'
  },
  module: {
    rules: [{
      test: /\.js$/,
      include: path.resolve(__dirname, 'src'),
      use: [{
        loader: 'babel-loader',
        options: {
          presets: [
  >         ['es2015', {moduels: false}]  
변경 후
  >          ['es2015', {modules: false}]

**Comment by pouu69** [comment]
수정완료 - 감사합니다.

https://github.com/FEDevelopers/tech.description/wiki/Webpack2와-모듈번들링을-위한-초보자-가이드/_compare/814bd0acac15c752c71c6098d6ae452a16911493...ca6a41fd1fa350c83356bbd244649eedea061b8b

**Comment by ppeeou** [comment]
좋은 자료 감사드립니다.
