### ISSUE TITLE
[오타신고]Webpack2와 모듈번들링을 위한 초보자 가이드

### ISSUE THREAD

**Issue by ppeeou** [FEDevelopers/tech.description#59]
// webpack.config.js
rules: [{
>  test: '/\.scss$/',

변경 후
> test: /\.scss$/

  use: [
    'style-loader',
    'css-loader',
    'sass-loader'
  ]
},{
  // ...
}]

**Comment by pouu69** [comment]
수정하였습니다. 
오타가 생각 보다 많았네요 확인한다고 했는데.. 따로 오타 이슈까지 남겨주셔서 감사드립니다.

https://github.com/FEDevelopers/tech.description/wiki/Webpack2와-모듈번들링을-위한-초보자-가이드/_compare/ca6a41fd1fa350c83356bbd244649eedea061b8b...f068a6f0a0d93765447bdabb6af1fcb68f04274d

**Comment by ppeeou** [comment]
자료를 공유 시켜주셔서 감사드려요 ~
