### ISSUE TITLE
[오류신고]Webpack2와 모듈번들링을 위한 초보자 가이드

### ISSUE THREAD

**Issue by ppeeou** [FEDevelopers/tech.description#60]
webpack을 재시작하면 새로운 번들인 
변경 전 
>app.bundle.js 

변경 후
>app.bundle.css 

을 볼수 있으며, 아래와 같이 바로 링크를 삽입 할 수 있습니다.

아래 코드
변경 전
`<link rel="stylesheet" href="dist/app.bundle.js">`

변경 후
`<link rel="stylesheet" href="dist/app.bundle.css">`

**Comment by pouu69** [comment]
ㅜㅜ 흠 이상하게 오타가 많네요 ㅜㅜ

**Comment by pouu69** [comment]
https://github.com/FEDevelopers/tech.description/wiki/Webpack2와-모듈번들링을-위한-초보자-가이드/_compare/f068a6f0a0d93765447bdabb6af1fcb68f04274d...07735b7a1805f5303d40c2153029f4368a3229a4

**Comment by ppeeou** [comment]
아직 이부분은 수정 안된 것 같습니다...!!!

webpack을 재시작하면 새로운 번들인
변경 전
>app.bundle.js

변경 후
>app.bundle.css

을 볼수 있으며, 아래와 같이 바로 링크를 삽입 할 수 있습니다.

**Comment by pouu69** [comment]
아... 놓쳤습니다. 이상하게 오타가.. 분명 오탈자 체크했는데...

**Comment by pouu69** [comment]
https://github.com/FEDevelopers/tech.description/wiki/Webpack2와-모듈번들링을-위한-초보자-가이드/_compare/07735b7a1805f5303d40c2153029f4368a3229a4...0cb0644885e678db5cc0fd4a084c781529a145a0
