### ISSUE TITLE
[오타신고] TDD기반 React,Redux,Immutable 시작하기 (1)

### ISSUE THREAD

**Issue by Jeewhan** [FEDevelopers/tech.description#64]
안녕하세요, 늘 좋은 글들 감사히 읽고 있습니다!

첫 번째 테스트 코드에서 'Redxu'이 'Redux'로 수정되어야 할 것 같습니다.
원문에서도 후자로 표기되어있습니다, 사소하지만 테스트 코드 통과와 관련되어있으므로 말씀드려봅니다...!

`expect(items[1].textContent).to.contain('Redxu');`

->

`expect(items[1].textContent).to.contain('Redux');`

감사합니다!

**Comment by pouu69** [comment]
수정완료
감사합니다.

https://github.com/FEDevelopers/tech.description/wiki/TDD기반-React,Redux,Immutable-시작하기-(1)/_compare/ba66d70b0d484a928c45441cf0ccd0d329da0601...b4554709aef4c8ccc0bd5e29f10008aaf6ad6f64
