### ISSUE TITLE
[오타신고] TDD기반 React,Redux,Immutable 시작하기 (1)

### ISSUE THREAD

**Issue by Jeewhan** [FEDevelopers/tech.description#65]
매우 사소한 것을 하나 더 발견하여 제보드립니다...!

`DOM class들을 조작하는데 조금 복잡니, classnames 패키지를 사용하겠습니다.`

->

`DOM class들을 조작하는데 조금 복잡하니, classnames 패키지를 사용하겠습니다.`

---

또한 글 최하단부에 아래 링크를 넣어주셔도 좋을 것 같습니다...!

https://github.com/FEDevelopers/tech.description/wiki/TDD기반-React,Redux,Immutable-시작하기-(2)

**Comment by pouu69** [comment]
수정완료
감사합니다.

https://github.com/FEDevelopers/tech.description/wiki/TDD%EA%B8%B0%EB%B0%98-React,Redux,Immutable-%EC%8B%9C%EC%9E%91%ED%95%98%EA%B8%B0-(1)/_compare/b4554709aef4c8ccc0bd5e29f10008aaf6ad6f64...fa1df9b2c6b5f0f5c100500989775f049fcb7f7d
