### ISSUE TITLE
[오타신고] Node.js Stream 당신이 알아야할 모든 것

### ISSUE THREAD

**Issue by pouu69** [FEDevelopers/tech.description#66]
1. `내용을 전부 메모리롤 올려 놓습니다` -> `내용을 전부 메모리를 올려 놓습니다`
2. `연결하였습니다. 소스은 읽기 가능한 ` -> `연결하였습니다. 소스는 읽기 가능한`
3. `물론 둘은 듀클랙스/트랜스폼 스트림이` -> `물론 둘은 듀플렉스/트랜스폼 스트림이`
4. `리눅스에서 하는 것처림 파이프 ` -> `리눅스에서 하는 것처럼 파이프 `
5. `두 가지 다른 태스트가 있습니다` -> `두 가지 다른 테스트가 있습니다.`
6. `굉장이 비슷해요.` -> `굉장히 비슷해요.`
7. `데이터를 달라고 요청할 대 말이죠 ` -> `데이터를 달라고 요청할 때 말이죠 `
8. `코드와 동일하지만의 소비자가 ` -> `코드와 동일하지만 소비자가 `
9. `위에 구했던 쓰기 스트림과 ` -> `위에서 구현했던 쓰기 스트림과 `
10. `메도드를 조합해서 A에서 ` -> `메소드를 조합해서 A에서 `

**Comment by jeonghwan-kim** [comment]
빠르게 수정하였습니다. @pouu69 님 짱
