### ISSUE TITLE
[오타제보] [ES6]객체지향 Javascript Class

### ISSUE THREAD

**Issue by drakejin** [FEDevelopers/tech.description#71]
## 제보 

- 제목 : [ES6]객체지향 Javascript Class
- 링크 : 
https://github.com/FEDevelopers/tech.description/wiki/%5BES6%5D%EA%B0%9D%EC%B2%B4%EC%A7%80%ED%96%A5-Javascript---Class

**제보내용**

마크다운에서 Header 선언 syntax가 제대로 물리지 않은거 같습니다 # {number} 가 되어야 하는데 #{number} 로 되어있어서 보기에 조금 어려움이 있습니다.

**Comment by pouu69** [comment]
https://github.com/FEDevelopers/tech.description/wiki/%5BES6%5D%EA%B0%9D%EC%B2%B4%EC%A7%80%ED%96%A5-Javascript---Class/_compare/fcf6c7ec4c51860c5fe3eca9999f1265e81823a6...ce8f5bfdd77623c9b84efffc4c8ea50684cfd48c
