### ISSUE TITLE
[오타신고] 자바스크립트에서 사용되는 this에 대한 설명 1

### ISSUE THREAD

**Issue by pouu69** [FEDevelopers/tech.description#72]
[메소드 실행](https://github.com/FEDevelopers/tech.description/wiki/%EC%9E%90%EB%B0%94%EC%8A%A4%ED%81%AC%EB%A6%BD%ED%8A%B8%EC%97%90%EC%84%9C-%EC%82%AC%EC%9A%A9%EB%90%98%EB%8A%94-this%EC%97%90-%EB%8C%80%ED%95%9C-%EC%84%A4%EB%AA%85-1#3-%EB%A9%94%EC%86%8C%EB%93%9C-%EC%8B%A4%ED%96%89)

````
helloFunction is a method in myObject. To get the method, use a property accessor: myObject.helloFunction. 여기서 helloFunction는 myOjbect의 메소드다. 메소드에 접근하기 위해서는 myObject.helloFunction와 같은 속성 접근자를 이용하면 된다.
````
->
````
여기서 helloFunction는 myOjbect의 메소드다. 메소드에 접근하기 위해서는 myObject.helloFunction와 같은 속성 접근자를 이용하면 된다.
````

**Comment by apple77y** [comment]
https://github.com/FEDevelopers/tech.description/wiki/%EC%9E%90%EB%B0%94%EC%8A%A4%ED%81%AC%EB%A6%BD%ED%8A%B8%EC%97%90%EC%84%9C-%EC%82%AC%EC%9A%A9%EB%90%98%EB%8A%94-this%EC%97%90-%EB%8C%80%ED%95%9C-%EC%84%A4%EB%AA%85-1/_compare/2fea991a3eedad0a7d8c7aa2bf2ff163783786fa...f4bbb17d4bedbd48dc5552cfb9e51b621f9a244d

수정!
