### ISSUE TITLE
마지막 함수 예제에 오류가 있습니다.

### ISSUE THREAD

**Issue by eniac5th** [FEDevelopers/tech.description#76]
fs.createReadStream(file)
  .pipe(crypto.createDecipher('aes192', 'a_secret'))
  .pipe(zlib.createGunzip())
  .pipe(reportProgress)
  .pipe(fs.createWriteStream(file.slice(0, -3)) ==> .pipe(fs.createWriteStream(file.slice(0, -3)))  // ')'하나가 없음
  .on('finish', () => console.log('Done'));

**Comment by apple77y** [comment]
https://github.com/FEDevelopers/tech.description/wiki/Node.js-Stream-%EB%8B%B9%EC%8B%A0%EC%9D%B4-%EC%95%8C%EC%95%84%EC%95%BC%ED%95%A0-%EB%AA%A8%EB%93%A0-%EA%B2%83

@jeonghwan-kim 님 여기 확인 부탁드릴게요

**Comment by jeonghwan-kim** [comment]
수정하였습니다.
제보 고맙습니다.
