### ISSUE TITLE
[오타신고] “typeof null”의 역사

### ISSUE THREAD

**Issue by taejs** [FEDevelopers/tech.description#80]
주소 : https://github.com/FEDevelopers/tech.description/wiki/%E2%80%9Ctypeof-null%E2%80%9D%EC%9D%98-%EC%97%AD%EC%82%AC

제목 :  “typeof null”의 역사

원문

undefined (JSVAL_VOID)은 정수 −230였다. (정수 범위를 벗어난 숫자).

수정 후

undefined (JSVAL_VOID)는 정수  −2<sup>30</sup>였다. (정수 범위를 벗어난 숫자).

**Comment by apple77y** [comment]
👍 감사합니다
