### ISSUE TITLE
어색한 문장 제보

### ISSUE THREAD

**Issue by HyunsangHan** [FEDevelopers/tech.description#81]
[함수형 프로그래머가 되고 싶다고? (Part 1)](https://github.com/FEDevelopers/tech.description/wiki/%ED%95%A8%EC%88%98%ED%98%95-%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8%EA%B0%80-%EB%90%98%EA%B3%A0-%EC%8B%B6%EB%8B%A4%EA%B3%A0%3F-(Part-1))를 읽는 도중 어색한 문장이 발견되어 제보합니다.

```
자바스크립트에서는 반복을 하기 위해 2가지가 있다.
```

**Comment by apple77y** [comment]
> 자바스크립트에서는 반복을 하기 위해서 사용하는 2가지 방법이 있다.

로 수정했습니다. 감사합니다! 👍
